modal & inner payment view
SoftRyzen-internship/vesta pull request #3
Opened 2024-01-26 14:43 UTC by opanchen

- виконано рефакторинг модального вікна з використанням сторонньої бібліотеки, видалено попередню реалізацію порталу;
- створено компонент списку платіжних реквізитів з реалізацією копіювання даних всередині;

PS: заголовок у модальне вікно передається окремо і рендериться за потреби - для кращої реюзабельності і використання внутрішньої реалізації заголовка від бібліотеки (з додатковими атрибутами і тд).

2024-01-26 16:02 UTC, nadiakhoptiuk requested changes

2024-01-26 16:02 UTC, nadiakhoptiuk commented on package.json
> +    "install": "^0.13.0",
що за пакет?)

2024-01-26 16:02 UTC, nadiakhoptiuk commented on src/components/ui/PaymentDetail/PaymentDetail.tsx
> +        className={`ml-auto hover:text-color-accent-hover focus-visible:text-color-accent-hover text-[12px] font-medium leading-[1.5] flex items-center gap-1 ${copied ? "text-color-accent-extra" : "t
1. виставити кнопці ширину, яка у неї є максимальна (тобто коли лейбл Скопійовано), бо скаче контент
2. думаю, варто дісейблити кнопку якщо copied = true, бо функція спрацьовує далі при кліку на неактивну
3. на неактивну прибрати ховер
4. додати перехід (слово transition обов'язково)

2024-01-26 16:02 UTC, nadiakhoptiuk commented on src/components/ui/PaymentDetail/PaymentDetail.tsx
> +    <div className="flex gap-8 items-center">
модалка має ширину 694 за макетом на десктоп, 580 - на таблет

2024-01-26 16:02 UTC, nadiakhoptiuk commented on src/components/ui/Modal/Modal.tsx
> +      <Transition show={isOpen} as={Fragment}>
модалка різко закривається. там є один нюанс, але вже не памятаю як я фіксила це (

2024-01-26 17:54 UTC, opanchen commented on package.json
> +    "install": "^0.13.0",
видалено

2024-01-26 17:54 UTC, opanchen commented on src/components/ui/PaymentDetail/PaymentDetail.tsx
> +        className={`ml-auto hover:text-color-accent-hover focus-visible:text-color-accent-hover text-[12px] font-medium leading-[1.5] flex items-center gap-1 ${copied ? "text-color-accent-extra" : "t
готово

2024-01-26 17:56 UTC, opanchen commented on src/components/ui/PaymentDetail/PaymentDetail.tsx
> +    <div className="flex gap-8 items-center">
задав ширину через пропс classNames для гнучкості на майбутнє, якщо будуть різні модалки різних розмірів

2024-01-26 17:57 UTC, opanchen commented on src/components/ui/Modal/Modal.tsx
> +      <Transition show={isOpen} as={Fragment}>
пішов шляхом внутрішньої стейт-машини, інакше анімація не встигає відпрацювати під час фаз монтування/розмонтування - реалізація мабуть не ідеальна, однак працює

2024-01-29 09:36 UTC, nadiakhoptiuk approved these changes

2024-01-29 09:37 UTC, merged